
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#777C85"
blue = "#6AB0F3"
cyan = "#76D4D6"
green = "#76D4D6"
magenta = "#E1A6F2"
red = "#F2777A"
white = "#FFFFFF"
yellow = "#FFEEA6"

[colors.normal]
black = "#2D2D2D"
blue = "#6AB0F3"
cyan = "#76D4D6"
green = "#92D192"
magenta = "#E1A6F2"
red = "#F2777A"
white = "#B3B9C5"
yellow = "#FFD479"

[colors.primary]
background = "#1D1F21"
foreground = "#FFFFFF"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "Meslo LGS Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "None"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = false
mods = "None"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]
